# Generated by Django 4.2.5 on 2025-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='shop_custom_last_na_d105df_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='shop_customer',
        ),
    ]
