# Generated by Django 4.2.5 on 2025-01-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='animal',
            field=models.CharField(choices=[('cow', 'Cow'), ('goat', 'Goat'), ('sheep', 'Sheep')], default='cow', max_length=8),
        ),
    ]
