# Generated by Django 4.2.5 on 2025-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cartitem_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kilo', 'Kilo'), ('quarter', 'Quarter'), ('half', 'Half'), ('full', 'Full')], default='kilo', max_length=8),
        ),
    ]
