# Generated by Django 4.2.5 on 2025-02-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
