# Generated by Django 4.2.5 on 2025-02-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_orderitem_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['user__first_name', 'user__last_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.customer',),
        ),
    ]
