# Generated by Django 5.1.6 on 2025-02-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_customerproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProxy',
        ),
    ]
